module.exports = {
  breadcrumbContainer: '.mantine-Breadcrumbs-root',
  breadcrumbHome: '.mantine-Anchor-root',
  breadcrumbOrg: '.mantine-Breadcrumbs-breadcrumb',
  searchInput: '.woswidgets-users-search input.rt-TextFieldInput',
  roleDropdown: '.woswidgets-select.rt-SelectTrigger',
  inviteButton: 'button.woswidgets-button--primary:has-text("Invite user")',
  tableRoot: '.rt-TableRootTable',
  tableRow: '.rt-TableRootTable tbody .rt-TableRow',
  tableHeaders: '.rt-TableRootTable thead .rt-TableColumnHeaderCell',
  roleMenu: '.rt-SelectContent[data-state="open"]',
  dialogRoot: '[data-state="open"][role="dialog"]',
  dialogEmailInput: 'input[placeholder="Enter an email address"], input[type="email"]',
  dialogRoleSelect: 'button[role="combobox"], button[aria-haspopup="listbox"]',
  dialogInviteBtn: 'button:has-text("Invite")',
  dialogCancelBtn: 'button:has-text("Cancel")',
  dialogRoleMenu: '[data-slot="menu-content"]',
  dialogAlert: 'section[aria-live="polite"]',
  modal: '[role="alertdialog"], [role="dialog"]',
  modalTitle: 'h1',
  modalConfirmBtn: 'button:has-text("Resend"), button:has-text("Revoke")',
  modalCancelBtn: 'button:has-text("Cancel")',
  userActionsBtn: 'button[title="User actions"]',
  firstRowMenuBtn: 'table tbody tr:first-child button[title="User actions"]',
  menuItemRevoke: 'role=menuitem >> text=Revoke invitation',
  menuItemResend: 'role=menuitem >> text=Resend',
  searchInputPlaceholder: 'input[placeholder="Search by name or e-mail"]',
  roleOption: 'role=option',
  inviteButton: 'button.woswidgets-button--primary:has-text("Invite user")',
  tableRoot: '.rt-TableRootTable',
  tableRow: '.rt-TableRootTable tbody .rt-TableRow',
  tableHeaders: '.rt-TableRootTable thead .rt-TableColumnHeaderCell',
  firstRowMenuBtn: 'table tbody tr:first-child button[title="User actions"]',
  dialogRoot: '[data-state="open"][role="dialog"]',
  dialogEmailInput: 'input[placeholder="Enter an email address"], input[type="email"]',
  dialogRoleSelect: 'button[role="combobox"], button[aria-haspopup="listbox"]',
  dialogInviteBtn: 'button:has-text("Invite")',
  dialogCancelBtn: 'button:has-text("Cancel")',
  dialogRoleMenu: '[data-slot="menu-content"]',
  dialogAlert: 'section[aria-live="polite"]',
  modal: '[role="alertdialog"], [role="dialog"]',
  modalTitle: 'h1',
  modalConfirmBtn: 'button:has-text("Resend"), button:has-text("Revoke")',
  modalCancelBtn: 'button:has-text("Cancel")',
  userActionsBtn: 'button[title="User actions"]',
  menuItemRevoke: 'role=menuitem >> text=Revoke invitation',
  menuItemResend: 'role=menuitem >> text=Resend'
};
