module.exports = {
  breadcrumbContainer: '.mantine-Breadcrumbs-root',
  breadcrumbHome: '.mantine-Anchor-root',
  breadcrumbOrg: '.mantine-Breadcrumbs-breadcrumb',
  searchInputPlaceholder: 'input[placeholder="Search by name or e-mail"]',
  roleDropdown: 'combobox',
  inviteButton: 'button:has-text("Invite user")',
  tableRoot: 'table.rt-TableRootTable',
  tableRow: 'table tbody tr.rt-TableRow',
  tableHeaders: 'table thead th.rt-TableColumnHeaderCell',
  roleMenu: '.rt-SelectContent[data-state="open"]',
  dialogRoot: '[role="dialog"]',
  dialogEmailInput: 'input[placeholder="Enter an email address"]',
  dialogRoleSelect: '[role="combobox"]',
  dialogInviteBtn: 'button:has-text("Invite")',
  dialogCancelBtn: 'button:has-text("Cancel")',
  modal: '[role="alertdialog"], [role="dialog"]',
  modalTitle: 'h1',
  modalConfirmBtn: 'button:has-text("Resend"), button:has-text("Revoke")',
  modalCancelBtn: 'button:has-text("Cancel")',
  userActionsBtn: 'button[title="User actions"]',
  firstRowMenuBtn: 'table tbody tr:first-child button[title="User actions"]',
  menuItemRevoke: 'role=menuitem >> text=Revoke invitation',
  menuItemResend: 'role=menuitem >> text=Resend'
};
