export const propertyLocators = {
    tableViewHeader: '.ag-header-cell .mantine-Text-root',
    tableScrollContainer: '.ag-center-cols-viewport',
    tableViewHeader: '.ag-header-cell .mantine-Text-root',
    tableScrollContainer: '.ag-center-cols-viewport',
    viewDetailsButton: 'button[title="View Details"]',
    tabs: tabName => `role=tab[name="${tabName}"]`,
    overviewFieldLabel: label => `text="${label}"`,
    overviewFieldValue: label => `xpath=//p[text()="${label}"]/./following-sibling::div//p`,
    propertyDocumentsTitle: 'p.mantine-Text-root:has-text("Property Documents")',
    uploadFilesButton: 'role=button[name="Upload Files"]',
    uploadDialog: 'dialog[open]',
    uploadFileInput: 'input[type="file"]',
    uploadListDialog: 'dialog[open] uc-upload-list',
    manageColumnsDrawer: 'section[role="dialog"]',
    tableSettingsButton: 'button:has(svg.lucide-settings)',
    viewDetailsBtn: 'button[title="View Details"]',
    documentsHeader: 'text=Property Documents',
    documentsSubHeader: 'text=Files and images related to this property',
    uploadFilesBtn: 'button:has-text("Upload Files")',
    tableHeaders: 'table thead th',
    tableRows: 'table tbody tr',
    tableRowCells: 'td',
    addDataButton: 'button[data-testid="bt-add-column"]',
    nameInput: 'input[placeholder^="Enter column name"]',
    descInput: 'input[placeholder^="Enter column description"]',
    typeButtons: 'div[style*="grid-template-columns"] button',
    submitAddColumn: 'button:has-text("Add column"):not([disabled])',

    propertiesNavLink: ".mantine-NavLink-root:has-text('Properties')",
    breadcrumbsProperties: ".mantine-Breadcrumbs-root:has-text('Properties')",
    createPropertyButton: "button:has-text('Create Property')",
    addPropertyModalHeader: ".mantine-Modal-header:has-text('Add property')",
    addressSuggestion: address => `.mantine-Autocomplete-option:has-text("${address}")`,
    propertyTypeOption: type => `.mantine-Select-option:has-text("${type}")`,
    propertiesBreadcrumbByName: name => `.mantine-Breadcrumbs-root:has-text('${name}')`,
    propertiesGridCardByName: name => `.mantine-SimpleGrid-root p:has-text('${name}')`,

    layoutListIcon: ".lucide.lucide-layout-list",
    viewMenuItemLabel: view => `.mantine-Menu-itemLabel:has-text('${view}')`,
    gridRootWrapper: ".ag-root-wrapper",
 
    filterPanelTitle: ".mantine-Paper-root p:has-text('Filter')",
    filterCheckbox: value => `input[value="${value}"]`,
    filterBadges: '.ag-center-cols-container .mantine-Badge-label',
    clearAllFiltersLink: '.mantine-Paper-root a:has-text("Clear All Filters")',

    downloadIcon: '.lucide-download',

    searchInput: 'input[placeholder="Search."]',
    firstRowNameCell: '.ag-center-cols-container div[role="row"] div[col-id="name"]',
    firstRowNameCellText: '.ag-center-cols-container div[role="row"] div[col-id="title"]',

    propertyNameCell: name => `.ag-center-cols-container p[title="${name}"], span:has-text("${name}")`,
    rowFromCell: "xpath=ancestor::div[@role='row']",
    rowDeleteIcon: rowIndex => `.ag-pinned-right-cols-container div[row-index="${rowIndex}"] .lucide-trash-2`,
    deleteButtonInPopover: '.mantine-Popover-dropdown button:has-text("Delete")',
    deleteConfirmBtn: ".mantine-Popover-dropdown button:has-text('Delete')",
    deleteColumnIcon: ".mantine-Group-root:has-text('Random Name') .lucide-trash2",
    addColumn: 'button[data-testid="bt-add-column"]',
    nameInputModal: 'input[placeholder^="Enter column name"]',
    descInput :'input[placeholder^="Enter column description"]',
    typeButtons :'div[style*="grid-template-columns"] button',
    submitButton :'button:has-text("Add column"):not([disabled])',
    interiorTab: 'button[role="tab"]:has-text("Interior")',
    exteriorTab: 'button[role="tab"]:has-text("Exterior")',
    assetViewer: 'button:has-text("Asset Viewer")',
    selectall: 'button:has-text("Select All")',
    selectNone: 'button:has-text("Select None")',
    cancelbtn: 'button:has-text("Cancel")',
    selectDownload: 'button:has-text("Download Selected")',


};
