name: Slack Regression Trigger

on:
  repository_dispatch:
    types: [run-regression]

jobs:
  trigger-playwright:
    runs-on: ubuntu-latest

    steps:

      - name: Trigger existing Playwright workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/playwright.yml/dispatches \
          -d '{"ref":"main","inputs":{"suite":"regression"}}'
